### ISSUE TITLE
HomeAssistant: vad end takes more time compared with the old one even in aggressive mode

### ISSUE THREAD

**Issue by VenominousX** [rhasspy/pymicro-vad#1]
Hi Synesthesiam,

with upgrading to Core 2024.8.1 the old vad was replaced with micro_vad, right?

After upgrading i am facing a performance drop at vad end. In the Assist Microphone Addon there is a option to adjust the vad end detection. In standard mode the vad end is detected after around 3 to 4 seconds. In aggressive mode, the vad end is also detected after around the same time, maybe one second faster.

Compared with the "old" vad now i have to wait 3 to 4 times longer than before until the intent was triggered. 
The accuracy is compareable between the 2 solutions.

Do you have some suggestions to improve perfomance? The "Assist Satellite" is a pi4 with HAOS installed. 

Best regards
Marcus

**Comment by ven-x** [comment]
It seems like this is fixed with the last home assistant update
